### 测试我们的算法

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [5]:
iris = datasets.load_iris()

In [7]:
X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
X.shape

(150, 4)

In [11]:
y.shape

(150,)

### train_test_split

In [12]:
shuffle_indexes = np.random.permutation(len(X)) # 形成一个150个索引的随机排列

In [13]:
shuffle_indexes

array([129, 126,  69,  80,  92, 139,  38, 116,  94,  18, 146,  10, 125,
        35,  39,  23,  56,  68,  97, 134,   3,  87,  65,   0,  37, 124,
        77,  45,  41, 130,  52, 132,   5, 119,  16,  30, 148,  99, 108,
        96,  70,  46,  42,  59,  40, 123, 140,  20, 114, 128,  29,  78,
        34,  31, 117,  84,  27, 121,  11,  95,  12,  75, 144,  54, 122,
        25,  21,  88, 149,  13,   8,   7, 118,  14, 133,  79,   9,  90,
        72, 145, 147, 112,  89,  64,  67, 109,  47,   1,  76,  93, 101,
        83,  62,  66, 135, 102,  53,  55, 120,  57, 143,  17,  48, 111,
       137,  82,  49,   6,  15,  74,  32, 106,  63,  58, 115, 138,  28,
       104,   4,   2, 141, 107,  19,  26, 142, 131, 127,  81,  60,  61,
        71,  51, 105, 100, 110, 103, 136,  36,  24,  86, 113,  98,  50,
        44,  22,  91,  33,  73,  85,  43])

In [14]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [15]:
test_size

30

In [16]:
test_indexes = shuffle_indexes[: test_size]
train_indexes = shuffle_indexes[test_size:]

In [17]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [20]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [21]:
%run Myscript/kNN/model_selection.py

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [25]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [36]:
%run Myscript/kNN/kNNv2.py

In [37]:
my_knn_clf = KNNClassifier(k = 3)

In [38]:
my_knn_clf.fit(X_train, y_train)

kNN(k=3)

In [39]:
y_predict = my_knn_clf.predict(X_test)

In [40]:
y_predict

array([1, 1, 1, 2, 0, 1, 0, 1, 1, 0, 2, 1, 2, 2, 2, 0, 2, 0, 0, 0, 1, 1,
       1, 1, 0, 2, 1, 1, 2, 0])

In [41]:
y_test

array([1, 1, 1, 2, 0, 1, 0, 1, 1, 0, 2, 1, 2, 2, 2, 0, 2, 0, 0, 0, 1, 1,
       1, 1, 0, 2, 1, 1, 2, 0])

In [42]:
sum(y_predict == y_test)  # true为1 ，false为0

30

In [43]:
sum(y_predict == y_test) / len(y_test)  # 准确率

1.0

### sklearn 中的 train_test_split

In [44]:
from sklearn.model_selection import train_test_split

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=666)   # random_state 随机种子

In [52]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)
