#                             Jupyter Notebook 高级-魔法命令

### %run

In [1]:
%run Myscript/test2.py

Hello Jerry !


In [2]:
hello("Tom")

Hello Tom !


In [10]:
import mymodule.TestModule

In [13]:
mymodule.TestModule.predict(1)

?


In [15]:
from mymodule import TestModule
TestModule.predict(1)

?


### %timeit

In [16]:
%timeit L = [i ** 2 for i in range(1000)]

462 µs ± 14.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [18]:
%timeit L = [i ** 2 for i in range(1000000)]

483 ms ± 7.22 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [19]:
%timeit L = [i ** 2 for i in range(10)]

4.62 µs ± 287 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
%%timeit
L = []
for n in range(1000):
    L.append(n ** 2)

500 µs ± 23.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### %time


In [21]:
%time L = [i ** 2 for i in range(1000)]

Wall time: 1 ms


In [22]:
%%time
L = []
for n in range(1000):
    L.append(n ** 2)

Wall time: 1.5 ms


In [24]:
import random
L = [random.random() for i in range(100000)]
%time L.sort()

Wall time: 23 ms


In [25]:
L = [random.random() for i in range(100000)]
%time L.sort()

Wall time: 25.5 ms


In [26]:
%time L.sort()

Wall time: 1.52 ms


### 其他魔法命令

In [27]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%py

In [28]:
%run?

In [29]:
import numpy
numpy.__version__

'1.15.1'

In [30]:
import numpy as np
np.__version__

'1.15.1'

# Python List 的特点

In [31]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
L[5]

5

In [33]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [35]:
L[5] = "Machine Learning"
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

# numpy
### numpy.array

In [37]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
nparr[5]

5

In [39]:
nparr[5] = "Machine Learning" #报错

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [40]:
nparr.dtype

dtype('int32')

In [41]:
nparr[5] = 5.0
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
nparr.dtype

dtype('int32')

In [43]:
nparr[3] = 3.14
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
nparr.dtype

dtype('int32')

In [46]:
nparr[3] = 3.6
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
nparr.dtype

dtype('int32')

In [50]:
nparr2 = np.array([1, 2, 3.0])
nparr2

array([1., 2., 3.])

In [51]:
nparr2.dtype

dtype('float64')

### 其他创建numpy.array的方法

In [52]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [53]:
np.zeros(10).dtype

dtype('float64')

In [56]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
np.zeros(shape = (3, 5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [60]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
np.full(shape = (3, 5), fill_value = 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

### arange

In [63]:
[i for i in range(0, 10, 2)]

[0, 2, 4, 6, 8]

In [64]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [65]:
[i for i in range(0, 10, .2)] #报错

TypeError: 'float' object cannot be interpreted as an integer

In [66]:
np.arange(0, 10, .2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

### linspace

In [68]:
np.linspace(0, 20, 10) # 包含终止点

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [69]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [71]:
np.random.randint(0, 10)

6

In [72]:
np.random.randint(0, 10, 10)

array([3, 0, 2, 7, 0, 4, 2, 5, 9, 1])

In [73]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [75]:
np.random.randint(4, 8, size = 10)

array([5, 4, 6, 7, 6, 6, 6, 6, 5, 7])

In [79]:
np.random.randint(4, 8, size=(3, 5))

array([[7, 7, 5, 5, 5],
       [6, 4, 7, 6, 6],
       [6, 5, 6, 6, 4]])

In [80]:
np.random.randint(4, 8, size=(3, 5))

array([[4, 4, 4, 4, 7],
       [4, 5, 4, 5, 5],
       [6, 7, 5, 6, 6]])

In [81]:
np.random.seed(666) # 随机种子
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [82]:
np.random.seed(666) # 随机种子
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [83]:
np.random.random()

0.2811684913927954

In [84]:
np.random.random(10)

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [89]:
np.random.random((3, 5))

array([[0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949],
       [0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981]])

In [94]:
np.random.normal() # 符合正态分布的随机浮点数  均值为0， 方差为0

1.078561378074435

In [95]:
np.random.normal(10, 100) # 符合均值为10， 方差为100 的随机数

-69.7835721331366

In [96]:
np.random.normal(0, 1, (3, 5))

array([[ 1.1701326 ,  0.1121217 ,  0.03185388, -0.19206285,  0.78611284],
       [-1.69046314, -0.98873907,  0.31398563,  0.39638567,  0.57656584],
       [-0.07019407,  0.91250436,  1.00470497,  0.41859929, -1.52902454]])

In [97]:
np.random.normal?

# Numpy 的基本操作

In [102]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [105]:
x.ndim

1

In [107]:
X.ndim

2

In [108]:
x.shape

(10,)

In [109]:
X.shape

(3, 5)

In [110]:
x.size

10

In [111]:
X.size

15

### numpy.array的数据访问

In [112]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
x[0]

0

In [115]:
x[-1]

9

In [116]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [117]:
X[2,2]

12

In [119]:
x[0:5]

array([0, 1, 2, 3, 4])

In [120]:
x[:5]

array([0, 1, 2, 3, 4])

In [121]:
x[5:]

array([5, 6, 7, 8, 9])

In [122]:
x[::2]

array([0, 2, 4, 6, 8])

In [123]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [124]:
x[::-2]

array([9, 7, 5, 3, 1])

In [125]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [126]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [127]:
X[:2, ::-1]

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

In [128]:
X[0]

array([0, 1, 2, 3, 4])

In [129]:
X[:, 0]

array([ 0,  5, 10])

In [131]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [134]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [135]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [137]:
X[0, 0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [138]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [140]:
subX = X[:2, :3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [142]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [143]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [144]:
x.shape

(10,)

In [145]:
x.ndim

1

In [147]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [148]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [151]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [154]:
B.ndim

2

In [155]:
x.reshape(10, -1) # -1自动计算

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [156]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [157]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [158]:
x.reshape(2, -1) # 报错

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 合并操作

In [160]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

In [161]:
a

array([1, 2, 3])

In [162]:
b

array([3, 2, 1])

In [164]:
np.concatenate([a, b])

array([1, 2, 3, 3, 2, 1])

In [166]:
c = np.array([666, 666, 666])
c

array([666, 666, 666])

In [167]:
np.concatenate([a, b, c])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [169]:
C = np.array([[1, 2, 3],
              [4, 5, 6]])
C

array([[1, 2, 3],
       [4, 5, 6]])

In [171]:
np.concatenate([C, C])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [172]:
np.concatenate([C, C], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [173]:
C.ndim

2

In [180]:
np.concatenate([C, c.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [181]:
np.vstack([C, c])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [182]:
D = np.full((2, 2), 100)
D

array([[100, 100],
       [100, 100]])

In [184]:
np.hstack([C, D])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割操作

In [187]:
d = np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [188]:
x1, x2, x3 = np.split(d, [3, 7])

In [189]:
x1

array([0, 1, 2])

In [190]:
x2

array([3, 4, 5, 6])

In [191]:
x3

array([7, 8, 9])

In [192]:
x1, x2 = np.split(d, [5])

In [193]:
x1

array([0, 1, 2, 3, 4])

In [194]:
x2

array([5, 6, 7, 8, 9])

In [201]:
E = np.arange(16).reshape((4, 4))
E

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [202]:
E1, E2 = np.split(E, [2])

In [203]:
E1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [204]:
E2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [206]:
E1, E2 = np.split(E, [2], axis = 1)

In [207]:
E1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [208]:
E2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [209]:
uper, lower = np.vsplit(E, [2])

In [210]:
uper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [211]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [212]:
left, right = np.hsplit(E, [2])

In [213]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [214]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [215]:
data = np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [217]:
X ,y = np.hsplit(data, [-1])

In [218]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [219]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [220]:
y[:, 0]

array([ 3,  7, 11, 15])

### numpy.array中的运算

In [221]:
n = 10
L = [i for i in range(n)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [222]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [224]:
A = []
for e in L:
    A.append(2 * e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [237]:
n = 1000000
L = [i for i in range(n)]

In [238]:
%%time
A = []
for e in L:
    A.append(2 * e)

Wall time: 233 ms


In [239]:
%%time
A = [2 * e for e in L]

Wall time: 145 ms


In [240]:
L = np.arange(n)

In [241]:
%%time
A = np.array(2 * e for e in L)

Wall time: 19 ms


In [243]:
%%time
A = 2 * L

Wall time: 4 ms


In [244]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [245]:
n = 10
L = np.arange(n)
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Universal Function

In [248]:
X = np.arange(1, 16).reshape((3, 5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [249]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [250]:
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [251]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [252]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [253]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [254]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [255]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [256]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [257]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [258]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [260]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [261]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [262]:
np.exp(X) # e的X次方

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [263]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [264]:
3 ** X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [265]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [266]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [267]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

### 矩阵运算

In [270]:
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [272]:
B = np.full((2, 2), 10)
B

array([[10, 10],
       [10, 10]])

In [273]:
A + B

array([[10, 11],
       [12, 13]])

In [275]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [276]:
A * B # 对应元素相乘的结果

array([[ 0, 10],
       [20, 30]])

In [277]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [278]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [279]:
A.T

array([[0, 2],
       [1, 3]])

### 向量和矩阵的运算

In [281]:
v = np.array([1, 2])
v

array([1, 2])

In [282]:
A

array([[0, 1],
       [2, 3]])

In [283]:
v + A

array([[1, 3],
       [3, 5]])

In [286]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [287]:
np.vstack([v] * A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [290]:
np.tile(v, (2, 1))

array([[1, 2],
       [1, 2]])

In [291]:
np.tile(v, (2, 1)) + A

array([[1, 3],
       [3, 5]])

In [294]:
v

array([1, 2])

In [295]:
A

array([[0, 1],
       [2, 3]])

In [293]:
v * A

array([[0, 2],
       [2, 6]])

In [296]:
v.dot(A)

array([4, 7])

In [297]:
A.dot(v)

array([2, 8])

### 矩阵的逆

#### 只有方阵才有逆矩阵， 不是方阵可以求伪逆矩阵

In [298]:
A 

array([[0, 1],
       [2, 3]])

In [300]:
invA = np.linalg.inv(A)
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [301]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [303]:
X = np.arange(16).reshape((2, 8))
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [304]:
pinvX = np.linalg.pinv(X)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.04083409e-17],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [306]:
X.dot(pinvX)

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

In [309]:
tmp = pinvX.dot(X)
tmp

array([[ 4.16666667e-01,  3.33333333e-01,  2.50000000e-01,
         1.66666667e-01,  8.33333333e-02,  3.05311332e-16,
        -8.33333333e-02, -1.66666667e-01],
       [ 3.33333333e-01,  2.73809524e-01,  2.14285714e-01,
         1.54761905e-01,  9.52380952e-02,  3.57142857e-02,
        -2.38095238e-02, -8.33333333e-02],
       [ 2.50000000e-01,  2.14285714e-01,  1.78571429e-01,
         1.42857143e-01,  1.07142857e-01,  7.14285714e-02,
         3.57142857e-02,  2.22044605e-16],
       [ 1.66666667e-01,  1.54761905e-01,  1.42857143e-01,
         1.30952381e-01,  1.19047619e-01,  1.07142857e-01,
         9.52380952e-02,  8.33333333e-02],
       [ 8.33333333e-02,  9.52380952e-02,  1.07142857e-01,
         1.19047619e-01,  1.30952381e-01,  1.42857143e-01,
         1.54761905e-01,  1.66666667e-01],
       [-8.32667268e-17,  3.57142857e-02,  7.14285714e-02,
         1.07142857e-01,  1.42857143e-01,  1.78571429e-01,
         2.14285714e-01,  2.50000000e-01],
       [-8.33333333e-02, -2.380952

In [311]:
tmp.shape

(8, 8)

### 聚合操作

In [312]:
L = np.random.random(100)

In [313]:
L

array([0.57773404, 0.89274848, 0.12138544, 0.66083873, 0.16459271,
       0.09435837, 0.5876144 , 0.86014445, 0.82936987, 0.65091808,
       0.51832728, 0.00355049, 0.80309176, 0.35932938, 0.42014544,
       0.2026436 , 0.63279787, 0.18935861, 0.1308497 , 0.75765845,
       0.34158167, 0.52138487, 0.88302327, 0.44914216, 0.23902229,
       0.33014086, 0.26650938, 0.79768204, 0.05551712, 0.12980746,
       0.82262638, 0.36076783, 0.56970121, 0.83023273, 0.44767601,
       0.2132831 , 0.56115445, 0.71657783, 0.7493205 , 0.58624783,
       0.54759891, 0.0817732 , 0.40852941, 0.63205157, 0.12168885,
       0.27480879, 0.07770505, 0.15726591, 0.14978044, 0.38535367,
       0.70941476, 0.44518764, 0.01584702, 0.99491381, 0.90632665,
       0.05199571, 0.86100897, 0.51224649, 0.0111548 , 0.49310591,
       0.55102356, 0.27260476, 0.2311436 , 0.95858105, 0.66579831,
       0.84015904, 0.14691185, 0.14394403, 0.30843116, 0.37016398,
       0.31852964, 0.56240025, 0.4640979 , 0.80066784, 0.78735

In [314]:
sum(L)

49.01446768914065

In [315]:
np.sum(L)

49.01446768914069

In [316]:
big_array = np.random.random(1000000)
%time sum(big_array)
%time np.sum(big_array)

Wall time: 158 ms
Wall time: 2 ms


500185.16831602337

In [317]:
np.max(big_array)

0.9999993748010294

In [318]:
np.min(big_array)

1.827632976070248e-06

In [319]:
big_array.min()

1.827632976070248e-06

In [320]:
big_array.max()

0.9999993748010294

In [322]:
big_array.sum()

500185.16831602337

In [330]:
A = np.arange(16).reshape(4, -1)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [331]:
np.sum(A)

120

In [332]:
np.sum(A, axis = 0)

array([24, 28, 32, 36])

In [333]:
np.sum(A, axis = 1)

array([ 6, 22, 38, 54])

In [337]:
np.prod(A) # 相乘

0

In [342]:
np.prod(A + 1)

2004189184

In [339]:
np.mean(A) # 平均值

7.5

In [340]:
np.median(X) # 中位数

7.5

In [344]:
np.percentile(big_array, q = 50)

0.5004360038440925

In [345]:
np.median(big_array)

0.5004360038440925

In [346]:
np.percentile(big_array, q = 100)

0.9999993748010294

In [347]:
np.max(big_array)

0.9999993748010294

In [348]:
for percent in [0, 25, 50, 100]:
    print (np.percentile(big_array, q = percent))

1.827632976070248e-06
0.2499891798320366
0.5004360038440925
0.9999993748010294


In [349]:
np.var(big_array) # 方差

0.08341609312793073

In [350]:
np.std(big_array) # 标准差

0.28881844319213884

In [351]:
x = np.random.normal(0, 1, size=1000000)

In [352]:
np.mean(x)

-0.0009171224804318551

In [354]:
np.std(x)

1.0022438716484598

### 索引

In [355]:
np.min(x)

-4.641802725097591

In [356]:
np.argmin(x)

159499

In [357]:
x[159499]

-4.641802725097591

In [359]:
np.argmax(x)

268670

In [360]:
x[268670]

5.279973136207795

In [361]:
np.max(x)

5.279973136207795

### 排序和使用索引

In [362]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [364]:
np.random.shuffle(x)
x

array([ 2,  5,  3, 15,  8,  1,  7,  0, 11, 10, 13,  9, 14,  4, 12,  6])

In [365]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [366]:
x

array([ 2,  5,  3, 15,  8,  1,  7,  0, 11, 10, 13,  9, 14,  4, 12,  6])

In [367]:
x.sort()

In [368]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [384]:
X = np.random.randint(10, size=(4, 4))
X

array([[6, 2, 6, 6],
       [4, 9, 6, 2],
       [3, 3, 4, 4],
       [6, 6, 1, 0]])

In [373]:
np.sort(X)

array([[4, 4, 8, 9],
       [0, 2, 6, 8],
       [0, 2, 7, 9],
       [1, 2, 6, 6]])

In [375]:
np.sort(X, axis=1)

array([[4, 4, 8, 9],
       [0, 2, 6, 8],
       [0, 2, 7, 9],
       [1, 2, 6, 6]])

In [377]:
np.sort(X, axis=0)

array([[0, 2, 6, 6],
       [0, 2, 6, 8],
       [1, 2, 7, 9],
       [4, 4, 8, 9]])

In [378]:
np.random.shuffle(x)
x

array([14,  4,  6,  7,  0,  5,  1,  2,  8, 10,  3, 11, 12, 13,  9, 15])

In [379]:
np.argsort(x)

array([ 4,  6,  7, 10,  1,  5,  2,  3,  8, 14,  9, 11, 12, 13,  0, 15],
      dtype=int64)

In [380]:
np.partition(x, 3)

array([ 1,  0,  2,  3,  7,  5,  6,  4,  8,  9, 10, 11, 12, 13, 14, 15])

In [382]:
np.argpartition(x, 3)

array([ 6,  4,  7, 10,  3,  5,  2,  1,  8, 14,  9, 11, 12, 13,  0, 15],
      dtype=int64)

In [385]:
X

array([[6, 2, 6, 6],
       [4, 9, 6, 2],
       [3, 3, 4, 4],
       [6, 6, 1, 0]])

In [387]:
np.argsort(X, axis=1)

array([[1, 0, 2, 3],
       [3, 0, 2, 1],
       [0, 1, 2, 3],
       [3, 2, 0, 1]], dtype=int64)

In [389]:
np.argsort(X, axis=0)

array([[2, 0, 3, 3],
       [1, 2, 2, 1],
       [0, 3, 0, 2],
       [3, 1, 1, 0]], dtype=int64)

In [390]:
np.argpartition(X, 2, axis=1)

array([[1, 0, 2, 3],
       [3, 0, 2, 1],
       [0, 1, 2, 3],
       [3, 2, 1, 0]], dtype=int64)

# Fancy Indexing

In [392]:
x = np.arange(16)

In [393]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [394]:
x[3]

3

In [395]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [396]:
x[3:9:2]

array([3, 5, 7])

In [397]:
ind =[3,5,8]

In [398]:
x[ind]

array([3, 5, 8])

In [400]:
ind = np.array([[0,2],[3,4]])
x[ind]

array([[0, 2],
       [3, 4]])

In [402]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [405]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [406]:
X[0, col]

array([1, 2, 3])

In [407]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [408]:
col = [True, False, True, False]

In [409]:
X[1:3, col]

array([[ 4,  6],
       [ 8, 10]])

### numpy.array的比较

In [410]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [411]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [412]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [413]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [414]:
x >= 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [415]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [416]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [418]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [422]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [423]:
x 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [426]:
np.sum(x <= 3)

4

In [427]:
np.count_nonzero(x <= 3)

4

In [428]:
np.any(x == 0)

True

In [429]:
np.all(x >= 0)

True

In [430]:
np.all(x > 0)

False

In [431]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [432]:
np.sum(X % 2 == 0)

8

In [434]:
np.sum(X % 2 == 0, axis=1)

array([2, 2, 2, 2])

In [435]:
np.sum(X % 2 == 0, axis=0)

array([4, 0, 4, 0])

In [436]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [437]:
np.sum((x > 5) & (x < 10))

4

In [438]:
np.sum((x % 2 == 0) | (x > 10))

11

In [439]:
np.sum(~(x == 0)) # 非

15

In [440]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [441]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [442]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [446]:
X[:, 3]

array([ 3,  7, 11, 15])

In [443]:
X[X[:, 3] % 3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])